services:
  - type: web
    name: digitano-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: AWS_REGION
        value: us-east-1
      - key: COGNITO_USER_POOL_ID
        value: us-east-1_Gx1XLOLRJ
      - key: COGNITO_APP_CLIENT_ID
        value: 408ssjnnva8r0p9adutse6q1ht
      - key: DYNAMODB_TABLE_NAME
        value: DigitanoProjects
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
